#!/usr/bin/env python
# coding: utf-8



import pandas as pd # pandas库导入
import numpy as np # numpy库导入


# # 标准行情接口
# 
# 下面是如何在程序里面调用本接口
# 
# **参数说明:**
# 
# - market: 对应市场。 (std 标准股票市场，ext 扩展市场)
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# ```
# 
# ### 其他参数
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std', multithread=True, heartbeat=True, bestip=True, timeout=15)
# # multithread 多线程
# # heartbeat 开启心跳包
# # bestip 重新测试最快服务器
# # timeout 设置超时时间
# ```
# 
# ## 01. 查询实时行情
# 
# 可以获取**多**只股票的行情信息
# 
# **参数说明:**
# 
# - symbol: 多个股票号码。 `["000001", "600300"]` 格式
# 
# 返回值：
# 
# - pd.DataFrame
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.quotes(symbol=["000001", "600300"])
# ```
# 
# ## 02. 获取k线数据
# 
# **调用方法：**
# 
# > frequency -> K线种类 0 5分钟K线 1 15分钟K线 2 30分钟K线 3 1小时K线 4 日K线 5 周K线 6 月K线 7 1分钟K线 8 1分钟K线 9 日K线 10 季K线 11 年K线
# 
# 如：
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.bars(symbol='600036', frequency=9, offset=10)
# 
# # 前复权
# client.bars(symbol='600036', adjust='qfq')
# 
# # 后复权
# client.bars(symbol='600036', adjust='hfq')
# ```
# 
# ## 03. 查询股票数量
# 
# **参数说明:**
# 
# - market: 市场代码. 0 - 深圳, 1 - 上海 (可以使用常量 `MARKET_SZ`, `MARKET_SH` 代替)
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# from mootdx import consts
# 
# client = Quotes.factory(market='std')
# client.stock_count(market=consts.MARKET_SH)
# ```
# 
# ## 04. 查询股票列表
# 
# **参数说明:**
# 
# - market: 市场代码. 0 - 深圳, 1 - 上海 (可以使用常量 `MARKET_SZ`, `MARKET_SH` 代替)
# 
# > 注意，在引入 consts 之后， （`from mootdx import consts`） 我们可以使用 consts.MARKET_SH , consts.MARKET_SZ 常量来代替 1 和 0 作为参数
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# from mootdx import consts
# 
# client = Quotes.factory(market='std')
# symbol = client.stocks(market=consts.MARKET_SH)
# ```
# 
# ## 05. 指数K线行情
# 
# **参数说明:**
# 
# - frequency: K线种类
# - market: 市场代码. 0 - 深圳, 1 - 上海 (可以使用常量 `MARKET_SZ`, `MARKET_SH` 代替)
# - start: 开始位置
# - offset: 用户要请求的 K 线数目，最大值为 800
# 
# > frequency: K线种类 0: 5分钟K线 1: 15分钟K线 2: 30分钟K线 3: 1小时K线 4: 日K线 5: 周K线 6: 月K线 7: 1分钟 8: 1分钟K线 9: 日K线 10: 季K线 11: 年K线
# 
# 使用说明：
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# from mootdx.consts import MARKET_SH
# 
# client = Quotes.factory(market='std')
# client.index(frequency=9, market=MARKET_SH, symbol='000001', start=1, offset=2)
# ```
# 
# ## 06. 查询分时行情
# 
# > 网友反馈，此接口数据有误，不建议使用，可以使用 后面的 `历史分时行情` 来替代
# 
# **参数说明:**
# 
# - symbol: 股票代码
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.minute(symbol='000001')
# 
# # 前复权
# client.minute(symbol='000001', adjust='qfq')
# 
# # 后复权
# client.minute(symbol='000001', adjust='hfq')
# ```
# 
# ## 07. 历史分时行情
# 
# **参数说明:**
# 
# - market: 市场代码.
# - symbol: 股票代码
# - date: 时间
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.minutes(symbol='000001', date='20171010')
# 
# # 前复权
# client.minutes(symbol='000001', date='20171010', adjust='qfq')
# 
# # 后复权
# client.minutes(symbol='000001', date='20171010', adjust='hfq')
# ```
# 
# 注意，在引入 consts 之后， （`from mootdx import consts`） 我们可以使用 consts.MARKET_SH , consts.MARKET_SZ 常量来代替 1 和 0 作为参数
# 
# ## 08. 查询分笔成交
# 
# **参数说明:**
# 
# - market: 市场代码.
# - start: 起始位置
# - offset: 数量
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.transaction(symbol='600036', start=0, offset=10)
# ```
# 
# ## 09. 查询历史分笔
# 
# **参数说明:**
# 
# - symbol: 股票代码.
# - start: 起始位置.
# - offset: 数量.
# - date: 日期.
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.transactions(symbol='000001', start=0, offset=10, date='20170209')
# ```
# 
# ## 10. 公司信息目录
# 
# **参数说明:** 市场代码， 股票代码， 如： 0,000001 或 1,600300
# 
# **参数说明:**
# 
# - symbol: 股票代码.
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.F10C(symbol='000001')
# ```
# 
# ## 11. 公司信息详情
# 
# **参数说明:**
# 
# - symbol: 股票代码.
# - name: 公司详情标题. 可使用`F10C`获取
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.F10(symbol='000001', name='最新提示')
# ```
# 
# 注意这里的 公司详情标题 参考上面接口的返回结果。
# 
# ## 12. 除权除息信息
# 
# **参数说明:**
# 
# - symbol: 股票代码.
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.xdxr(symbol='600036')
# ```
# 
# ## 13. 读取财务信息
# 
# **参数说明:**
# 
# - symbol: 股票代码.
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.finance(symbol="600300")
# ```
# 
# ## 14. 读取k线信息
# 
# **参数说明:**
# 
# - symbol: 股票代码.
# - begin: 开始时间.
# - end: 结束时间.
# 
# **调用方法：**
# 
# ```python
# from mootdx.quotes import Quotes
# 
# client = Quotes.factory(market='std')
# client.k(symbol="600300", begin="2017-07-03", end="2017-07-10")
# ```



# 标准行情接口
from mootdx.quotes import Quotes
# 参数说明:
# market: 对应市场。 (std 标准股票市场，ext 扩展市场)
# multithread 多线程
# heartbeat 开启心跳包
# bestip 重新测试最快服务器
# timeout 设置超时时间

#client = Quotes.factory(market='std', multithread=True, heartbeat=True, bestip=True, timeout=15)
client = Quotes.factory(market='std')




# 查询实时行情
"""可以获取多只股票的行情信息
   参数说明:
   symbol: 多个股票号码。 ["000001", "600300"] 格式
   返回值：
   pd.DataFrame
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
client.quotes(symbol=["000001", "600300"])




# 获取k线数据
"""调用方法：
   frequency -> K线种类 0 5分钟K线 1 15分钟K线 2 30分钟K线 3 1小时K线 4 日K线 5 周K线 6 月K线 7 1分钟K线 8 1分钟K线 9 日K线 10 季K线 11 年K线
client.bars(symbol='600036', frequency=9, offset=10)
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
# 前复权
# client.bars(symbol='600036', adjust='qfq')
# 后复权
client.bars(symbol='600036') #, adjust='hfq')

# 前后复权参数异常




# 查询股票数量
"""参数说明:
   market: 市场代码. 0 - 深圳, 1 - 上海 (可以使用常量 MARKET_SZ, MARKET_SH 代替)
"""
from mootdx.quotes import Quotes
from mootdx import consts
client = Quotes.factory(market='std')
client.stock_count(market=consts.MARKET_SH)




# 查询股票列表
"""参数说明:
   market: 市场代码. 0 - 深圳, 1 - 上海 (可以使用常量 MARKET_SZ, MARKET_SH 代替)
   注意，在引入 consts 之后， （from mootdx import consts） 我们可以使用 consts.MARKET_SH , consts.MARKET_SZ 常量来代替 1 和 0 作为参数
"""
from mootdx.quotes import Quotes
from mootdx import consts
client = Quotes.factory(market='std')
symbol = client.stocks(market=consts.MARKET_SH)


# 指数K线行情
"""参数说明:
frequency: K线种类
market: 市场代码. 0 - 深圳, 1 - 上海 (可以使用常量 MARKET_SZ, MARKET_SH 代替)
start: 开始位置
offset: 用户要请求的 K 线数目，最大值为 800
frequency: K线种类 0: 5分钟K线 1: 15分钟K线 2: 30分钟K线 3: 1小时K线 4: 日K线 5: 周K线 6: 月K线 7: 1分钟 8: 1分钟K线 9: 日K线 10: 季K线 11: 年K线
"""
from mootdx.quotes import Quotes
from mootdx.consts import MARKET_SH
client = Quotes.factory(market='std')
client.index(frequency=9, market=MARKET_SH, symbol='000001', start=1, offset=2)


# 历史分时行情
"""参数说明:
market: 市场代码.
symbol: 股票代码
date: 时间
注意，在引入 consts 之后， （from mootdx import consts） 我们可以使用 consts.MARKET_SH , consts.MARKET_SZ 常量来代替 1 和 0 作为参数
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
client.minutes(symbol='000001', date='20171010')




# 前复权
client.minutes(symbol='000001', date='20171010') #, adjust='qfq')
# 后复权
# client.minutes(symbol='000001', date='20171010', adjust='hfq')

# 前后复权参数无效




# 查询分笔成交
"""参数说明:
market: 市场代码.
start: 起始位置
offset: 数量
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
client.transaction(symbol='600036', start=0, offset=10)




# 查询历史分笔
"""参数说明:
symbol: 股票代码.
start: 起始位置.
offset: 数量.
date: 日期.
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
client.transactions(symbol='000001', start=0, offset=10, date='20170209')




# 公司信息目录
"""参数说明: 市场代码， 股票代码， 如： 0,000001 或 1,600300
参数说明:
symbol: 股票代码.
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
client.F10C(symbol='000001')




# 公司信息详情
"""参数说明:
symbol: 股票代码.
name: 公司详情标题. 可使用F10C获取
注意这里的 公司详情标题 参考上面接口的返回结果。
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
client.F10(symbol='000001', name='最新提示')




# 除权除息信息
"""参数说明:
symbol: 股票代码.
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
client.xdxr(symbol='600036')




# 读取财务信息
"""参数说明:
symbol: 股票代码.
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
client.finance(symbol="600300")




# 读取k线信息
"""参数说明:
symbol: 股票代码.
begin: 开始时间.
end: 结束时间.
"""
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
client.k(symbol="600300", begin="2017-07-03", end="2017-07-10")


# ## 离线数据接口
# 
# 通过下面的接口，我们可以解析日K线文件，该文件可以通过读取软件本地目录导出的数据获取，也可以从官网上下载， 如果您安装了终端，可以在安装目录下找到 `vipdoc` 子目录。
# 
# 比如我的客户端安装在 `c:\new_tdx` 下，
# 
# 即
# 
# - `C:/new_tdx/vipdoc/sz/lday/` 下是深圳的日k线数据
# - `C:/new_tdx/vipdoc/sh/lday/` 下是上海的日k线数据
# 
# 该目录下每个股票为一个文件，如 `sz000001.day` 为深圳的日k行情，
# 
# ### 01. 读取行情接口
# 
# ```python
# from mootdx.reader import Reader
# 
# reader = Reader.factory(market='std', tdxdir='C:/new_tdx')
# 
# # 读取日线数据
# reader.daily(symbol='600036')
# 
# # 读取1分钟数据
# reader.minute(symbol='600036')
# 
# # 读取5分钟数据
# reader.fzline(symbol='600036')
# ```
# 
# ## 02. 读取扩展行情
# 
# > 读取扩展行情的日线（如期货，期权，现货等）
# 
# ```python
# from mootdx.reader import Reader
# 
# reader = Reader.factory(market='ext', tdxdir='c:/new_tdx')
# reader.daily(symbol='29#A1801')
# ```
# 
# ## 03. 历史分钟数据
# 
# > 读取分钟K线（目前支持1，5分钟k线）
# 
# 分钟线有两种格式，第一种是`.1` `.5` 为后缀的, 还有一种为 `.lc1` `.lc5` 后缀的. 不过不用考虑，接口会自动判断
# 
# ```python
# from mootdx.reader import Reader
# 
# reader = Reader.factory(market='std', tdxdir='c:/new_tdx')
# reader.minute(symbol='000001', suffix='1')  # suffix = 1 一分钟，5 五分钟
# ```
# 
# 扩展数据接口读取方式
# 
# ```python
# from mootdx.reader import Reader
# 
# reader = Reader.factory(market='ext', tdxdir='c:/new_tdx')
# reader.minute(symbol='000001', suffix='1')  # suffix = 1 一分钟，5 五分钟
# ```
# 
# ## 04. 读取板块信息
# 
# 文件位置参考： http://blog.sina.com.cn/s/blog_623d2d280102vt8y.html
# 
# 样例代码：
# 
# ```python
# from mootdx.reader import Reader
# 
# reader = Reader.factory(market='std', tdxdir='c:/new_tdx')
# reader.block(symbol='block_zs', group=False)
# # 分组格式
# from mootdx.reader import Reader
# reader = Reader.factory(market='std', tdxdir='c:/new_tdx')
# 
# reader.block(symbol='block_zs', group=True)
# ```
# 
# ## 05. 自定义板块数据
# 
# > 读取自定义板块信息文件夹
# 
# ```python
# from mootdx.reader import Reader
# 
# reader = Reader.factory(market='std', tdxdir='C:/new_tdx')
# 
# # 默认扁平格式
# reader.block_new()
# 
# # 分组格式
# reader.block_new(group=True)
# ```
# 
# 写入新板块
# 
# ```python
# # 写入新板块
# from mootdx.reader import Reader
# 
# reader = Reader.factory(market='std', tdxdir='C:/new_tdx')
# reader.block_new(name='最优盈利板块', symbol=['600001', '600002', '600003', '600004', ])
# ```



# 读取行情接口
from mootdx.reader import Reader
reader = Reader.factory(market='std', tdxdir='D:/OtherPrograms/new_jyplug')




# 读取日线数据
reader。daily(symbol='600036')

# 读取1分钟数据
reader。minute(symbol='600036')

# 读取5分钟数据
reader。fzline(symbol='600036')




## 读取扩展行情
"""读取扩展行情的日线（如期货，期权，现货等）"""
from mootdx.reader import Reader
reader = Reader.factory(market='std', tdxdir='D:/OtherPrograms/new_jyplug')
reader。daily(symbol='29#A1801')




## 历史分钟数据
"""读取分钟K线（目前支持1，5分钟k线）
分钟线有两种格式，第一种是`.1` `.5` 为后缀的, 还有一种为 `.lc1` `.lc5` 后缀的. 不过不用考虑，接口会自动判断
"""
from mootdx.reader import Reader
reader = Reader.factory(market='std', tdxdir='D:/OtherPrograms/new_jyplug')
reader。minute(symbol='000001', suffix='1')  # suffix = 1 一分钟，5 五分钟




# 扩展数据接口读取方式
from mootdx.reader import Reader
reader = Reader.factory(market='std', tdxdir='D:/OtherPrograms/new_jyplug')
reader。minute(symbol='000001', suffix='1')  # suffix = 1 一分钟，5 五分钟




# 读取板块信息
from mootdx.reader import Reader
reader = Reader.factory(market='std', tdxdir='D:/OtherPrograms/new_jyplug')
reader。block(symbol='block_zs', group=False)




# 分组格式
from mootdx.reader import Reader
reader = Reader.factory(market='std', tdxdir='D:/OtherPrograms/new_jyplug')
reader。block(symbol='block_zs', group=True)




## 自定义板块数据
"""读取自定义板块信息文件夹"""
from mootdx.reader import Reader
reader = Reader.factory(market='std', tdxdir='D:/OtherPrograms/new_jyplug')
# 默认扁平格式
reader.block_new()




# 分组格式
reader.block_new(group=True)




# 写入新板块
from mootdx.reader import Reader
reader = Reader.factory(market='std', tdxdir='D:/OtherPrograms/new_jyplug')
reader.block_new(name='最优盈利板块', symbol=['600001', '600002', '600003', '600004', ])

